# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core app to Azure Function App - fct-lotofacil-loader

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'output' # pasta com o conteúdo publicado para deploy
  FUNCTIONAPP_PROJECT_PATH: 'src/FunctionApp/Lotofacil.Loader.FunctionApp.csproj'
  DOTNET_VERSION: '8.0.x' # o projeto alvo está em net8.0

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          dotnet restore '${{ env.FUNCTIONAPP_PROJECT_PATH }}'
          dotnet publish '${{ env.FUNCTIONAPP_PROJECT_PATH }}' --configuration Release --output '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1DE6AEE701D541349F778298BF4B6DBE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E1A92D1D28514E1CA6CDAC7773182578 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_10C8A4064B10484A85957DD0898A5490 }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'fct-lotofacil-loader'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          